export const CONFIG = {
  PORT: process.env.PORT || 4000,
  MAIN_DATA_POLL_INTERVAL: 60000,
  EVENT_STREAM_POLL_INTERVAL: 5000,
  CORS_ORIGIN: "http://localhost:5173",
  SOCKET_CONFIG: {
    cors: {
      origin: "http://localhost:5173",
      methods: ["GET", "POST"],
    },
    pingTimeout: 60000,
    pingInterval: 25000,
  },
  CACHE_TTL: 5 * 60 * 1000,
  QUERY_TIMEOUT: 600000,
  MAX_ROWS: 100000,
  MAX_POLL_ATTEMPTS: 180,
  INITIAL_POLL_DELAY: 1000,
  MAX_POLL_DELAY: 10000,
  EVENT_TYPES: [
    "page view",
    "add to basket",
    "remove from basket",
    "purchase",
    "cms viewable impression",
    "cms component item click",
    "add to loves",
    "un love",
  ],
  LIVESTREAMEVENT_EVENT_TYPES: [
    "add to basket",
    "remove from basket",
    "purchase",
    "add to loves",
    "un love",
  ],
  PLATFORMS: [
    "desktop web",
    "mobile web",
    "tablet web",
    "android app",
    "iphone app",
  ],
};